title: Hello, Wellcome to Hackerhut
description: We are Software Security Professionals passionate about AppSec, IoT, Hardware & Wireless Security.
permalink: ':title/'
baseurl: "/hackerhut" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: HACKERHUT(h4k3rhut)
author-img: h4k3rhut.png # add your photo
about-author: We are Software Security Professionals passionate about AppSec, IoT, Hardware & Wireless Security. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: ankush.h4k3rhut@icloud.com # add your Email address

# Disqus
discus-identifier: h4k3rhut # add your discus identifier

# Tracker
analytics: https://www.googletagmanager.com/gtag/js?id=UA-177345232-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
